apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: ecommerce-app
  labels:
    app: ecommerce
    component: backend
    version: v1.0.0
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  
  minReplicas: 2
  maxReplicas: 5  # As specified in requirements
  
  # Scaling behavior configuration
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      policies:
      - type: Percent
        value: 50  # Scale down max 50% of current replicas
        periodSeconds: 60
      - type: Pods
        value: 1  # Or remove max 1 pod per minute
        periodSeconds: 60
      selectPolicy: Min  # Use the most conservative policy
    scaleUp:
      stabilizationWindowSeconds: 0  # Scale up immediately
      policies:
      - type: Percent
        value: 100  # Double the replicas
        periodSeconds: 30
      - type: Pods
        value: 2  # Or add max 2 pods
        periodSeconds: 30
      selectPolicy: Max  # Use the most aggressive policy
  
  # Metrics to scale on - CPU only as per requirements
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Scale when CPU > 70% (as specified in requirements)
