{{- if and .Values.frontend.enabled .Values.frontend.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ecommerce-app.fullname" . }}-frontend
  namespace: {{ include "ecommerce-app.namespace" . }}
  labels:
{{ include "ecommerce-app.labels" . | indent 4 }}
    component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ecommerce-app.fullname" . }}-frontend
  minReplicas: {{ .Values.frontend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.frontend.autoscaling.maxReplicas }}
  behavior:
{{ toYaml .Values.frontend.autoscaling.behavior | indent 4 }}
  metrics:
{{- if .Values.frontend.autoscaling.cpu }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.frontend.autoscaling.cpu }}
{{- end }}
{{- if .Values.frontend.autoscaling.memory }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.frontend.autoscaling.memory }}
{{- end }}
{{- end }}
