{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name | default (printf "%s-secrets" (include "ecommerce-app.fullname" .)) }}
  namespace: {{ include "ecommerce-app.namespace" . }}
  labels:
{{ include "ecommerce-app.labels" . | indent 4 }}
    component: secrets
    app: ecommerce
    environment: development
stringData:
  DATABASE_URL: {{ quote .Values.secrets.databaseUrl }}
  REDIS_PASSWORD: {{ quote .Values.secrets.redisPassword }}
  JWT_SECRET: {{ quote .Values.secrets.jwtSecret }}
  API_KEY: {{ quote .Values.secrets.apiKey }}
{{- end }}
