{{- if .Values.serviceAccounts.frontend.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-frontend" (include "ecommerce-app.fullname" .)) .Values.serviceAccounts.frontend.name }}
  namespace: {{ include "ecommerce-app.namespace" . }}
  labels:
{{ include "ecommerce-app.labels" . | indent 4 }}
    component: frontend
{{- end }}
---
{{- if .Values.serviceAccounts.backend.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-backend" (include "ecommerce-app.fullname" .)) .Values.serviceAccounts.backend.name }}
  namespace: {{ include "ecommerce-app.namespace" . }}
  labels:
{{ include "ecommerce-app.labels" . | indent 4 }}
    component: backend
{{- end }}
