---
# SecretProviderClass for Azure Key Vault integration (Uncomment in Azure)
# This requires Azure Key Vault Provider for Secrets Store CSI Driver
# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: azure-keyvault-secrets
#   namespace: ecommerce-app
#   labels:
#     app: ecommerce
#     component: secrets
# spec:
#   provider: azure
#   parameters:
#     usePodIdentity: "false"
#     useVMManagedIdentity: "false"
#     # Azure Workload Identity
#     clientID: ""  # Set via Azure Workload Identity
#     keyvaultName: "ecommerce-kv"  # Replace with your Key Vault name
#     cloudName: "AzurePublicCloud"
#     tenantId: ""  # Your Azure tenant ID
#     objects: |
#       array:
#         - |
#           objectName: database-connection-string
#           objectType: secret
#           objectVersion: ""
#         - |
#           objectName: redis-password
#           objectType: secret
#           objectVersion: ""
#         - |
#           objectName: jwt-secret
#           objectType: secret
#           objectVersion: ""
#   # Create Kubernetes secrets from Key Vault objects
#   secretObjects:
#   - secretName: ecommerce-secrets
#     type: Opaque
#     data:
#     - objectName: database-connection-string
#       key: DATABASE_URL
#     - objectName: redis-password
#       key: REDIS_PASSWORD
#     - objectName: jwt-secret
#       key: JWT_SECRET

---
# Fallback: Basic Kubernetes Secret for local/dev environments
# In production, use SecretProviderClass above with Azure Key Vault
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets-local
  namespace: ecommerce-app
  labels:
    app: ecommerce
    component: secrets
    environment: development
type: Opaque
stringData:
  # Database connection string
  DATABASE_URL: "postgresql://ecommerce_user:changeme@postgres-service:5432/ecommerce_db"
  
  # Redis password (if using Redis with auth)
  REDIS_PASSWORD: ""
  
  # JWT secret for authentication tokens
  JWT_SECRET: "change-this-in-production-use-key-vault"
  
  # API keys or other sensitive data
  API_KEY: "development-key"
