---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecommerce-frontend-sa
  namespace: ecommerce-app
  labels:
    app: ecommerce
    component: frontend
    version: v1.0.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecommerce-backend-sa
  namespace: ecommerce-app
  labels:
    app: ecommerce
    component: backend
    version: v1.0.0
